#!/usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x polybar > /dev/null || $HOME/.config/polybar/launch.sh &
pgrep -x feh > /dev/null || feh --hide-pointer --bg-scale -qrzFD 360.0 ~/Pictures/z-w-gu_wallpapers &
pgrep -x blueman-applet > /dev/null || blueman-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Google-chrome-beta desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
