#!/usr/bin/env bash

<< '////'
MIT License

Copyright (c) [2022] [Qark-dev<qarkdev@gmail.com>]

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
////

# {{{ Hotkey daemon - bspwm does not have a keybinding impl
    pgrep -x sxhkd > /dev/null || sxhkd &
# }}}

# {{{ bspwm config
    bspc monitor -d Chat Code Crawl Cafe C 

    bspc config border_width        2
    bspc config window_gap          12

    bspc config split_ratio         0.52
    bspc config borderless_monocle  true
    bspc config gapless_monocle     true

    bspc rule -a Gimp desktop='^8' state=floating follow=on
    bspc rule -a mplayer2 state=floating
    bspc rule -a Kupfer.py focus=on
    bspc rule -a Screenkey manage=off

    bspc rule -a Peek state=floating
    bspc rule -a screengrab state=floating

    bspc rule -a discord desktop='^1' 
    bspc rule -a Code\ -\ Insiders desktop='^2'

    bspc rule -a Google-chrome-beta desktop='^3' -o

    bspc rule -a Blueman-manager desktop='^4'
    bspc rule -a Pavucontrol desktop='^4'
    bspc rule -a Steam desktop='^5'
# }}}

# {{{ Autostarts
    # Compositor for window translucency
    picom &

    # Polybar
    $HOME/.config/polybar/launch.sh &

    # Feh for background image - set to change every 5 minutes
    pgrep -x feh > /dev/null || feh --hide-pointer --bg-scale -qrzFD 360.0 ~/Pictures/z-w-gu_wallpapers &
    
    # Make sure that blueman-applet is running before we can run blueman-nanager
    pgrep -x blueman-applet > /dev/null || blueman-applet &

    # Make sure our network manager applet is up
    pgrep -x nm-applet > /dev/null || nm-applet &

    pgrep -x chrome > /dev/null || google-chrome-beta  &
    pgrep -x code-insiders > /dev/null || code-insiders &
    pgrep -x discord > /dev/null || discord &

    pgrep -x steam > /dev/null || steam &
    blueman-manager &
    pavucontrol &  
    pgrep -x ncmpcpp > /dev/null || alacritty -e ncmpcpp &
# }}}
